DROP TABLE SHOES_STOCK IF EXISTS;
CREATE TABLE SHOES_STOCK (
                      stock_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                      color varchar(12) not null,
                      inputDate DATE DEFAULT CURRENT_DATE,
                      outputDate DATE DEFAULT NULL,
                      size integer not null
);